---
openshift_cluster_content:
- object: deployments
  content:
  - name: basic-tomcat-dev
    template: "{{ inventory_dir }}/../files/deployment/template.yml"
    params: "{{ inventory_dir }}/../files/deployment/dev/params"
  - name: basic-tomcat-stage
    template: "{{ inventory_dir }}/../files/deployment/template.yml"
    params: "{{ inventory_dir }}/../files/deployment/stage/params"
  - name: basic-tomcat-prod
    template: "{{ inventory_dir }}/../files/deployment/template-bg.yml"
    params: "{{ inventory_dir }}/../files/deployment/prod/params"
- object: builds
  content:
  - name: jenkins
    template: "{{ inventory_dir }}/../files/builds/template.yml"
    params: "{{ inventory_dir }}/../files/builds/params"
