---
apiVersion: v1
kind: Template
labels:
  template: mule-build-ee-template
message: A Jenkins build-config template
metadata:
  annotations:
    description: |-
        Jenkins build config template
    iconClass: icon-mule
    tags: instant-app,mule
  name: mule-ee
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: mule-ee-ephemeral
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${MULE_SERVICE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: mule-ee-ephemeral:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/${GITHUB_ORG}/jenkins-s2i-configuration
        ref: ${GITHUB_REF}
      type: Git
      contextDir: ./mule
    strategy:
      dockerStrategy:
          noCache: true
          forcePull: true
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange

parameters:
- description: The name of the github organization to reference in the configuration
  displayName: Github Organization
  name: GITHUB_ORG
  value: dwaiba
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: GITHUB_REF
  value: master
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Mule Service Name
  name: MULE_SERVICE_NAME
  value: mule

