---
apiVersion: v1
kind: Template
labels:
  template: mule-image-ee-template
message: A mule build-config template
metadata:
  annotations:
    description: |-
        Jenkins build config template 
    iconClass: icon-mule
    tags: instant-app,mule
  name: mule-ee
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${MULE_SERVICE_NAME}
  spec:
    dockerImageRepository: "openshift/mule-ee-ephemeral"
parameters:
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: MULE_SERVICE_NAME
  value: mule
