---
apiVersion: v1
kind: Template
labels:
  template: nexus3-build-template
message: A nexus3 build-config template
metadata:
  annotations:
    description: |-
        nexus3 build config template
    iconClass: icon-nexus3
    tags: instant-app,nexus3
  name: nexus3-ose
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nexusephemeral
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NEXUS_SERVICE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nexusephemeral:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/${GITHUB_ORG}/jenkins-s2i-configuration
        ref: ${GITHUB_REF}
      type: Git
      contextDir: ./nexus3
    strategy:
      dockerStrategy:
          noCache: true
          forcePull: true
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange

parameters:
- description: The name of the github organization to reference in the configuration
  displayName: Github Organization
  name: GITHUB_ORG
  value: dwaiba
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: GITHUB_REF
  value: master
- description: The name of the OpenShift Service exposed for the Nexus3 container.
  displayName: Nexus3 Service Name
  name: NEXUS_SERVICE_NAME
  value: nexus3
