---
kind: Template
apiVersion: v1
metadata:
  name: nexus3-ose
  creationTimestamp:
  annotations:
    openshift.io/display-name: Nexus3 (nexusephemeral)
    description: |-
      Nexus3 service
    tags: instant-app,nexus3
    template.openshift.io/long-description: This template deploys a Nexus3 server
      capable of managing OpenShift Pipeline builds and supporting OpenShift-based
      oauth login.
    template.openshift.io/provider-display-name: dwaiba.
message: A Nexus3 service has been created in your project. 
objects:
- kind: Route
  apiVersion: v1
  metadata:
    name: "${NEXUS_SERVICE_NAME}"
    creationTimestamp:
  spec:
    to:
      kind: Service
      name: "${NEXUS_SERVICE_NAME}"
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/scc: privileged
    name: "${NEXUS_SERVICE_NAME}"
    creationTimestamp:
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - nexus3
        from:
          kind: ImageStreamTag
          name: "${NEXUS_IMAGE_STREAM_TAG}"
          namespace: "${NAMESPACE}"
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${NEXUS_SERVICE_NAME}"
    template:
      metadata:
        creationTimestamp:
        labels:
          name: "${NEXUS_SERVICE_NAME}"
      spec:
        serviceAccountName: "${NEXUS_SERVICE_NAME}"
        containers:
        - name: nexus3
          image: " "
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 3
            httpGet:
              path: "/"
              port: 8081
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 420
            failureThreshold: 30
            httpGet:
              path: "/"
              port: 8081
          env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "${ENABLE_OAUTH}"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: 'true'
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: 'true'
          - name: NEXUS_SERVICE_NAME
            value: "${NEXUS_SERVICE_NAME}"
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        dnsPolicy: ClusterFirst
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${NEXUS_SERVICE_NAME}"
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.nexus3: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${NEXUS_SERVICE_NAME}"}}'
- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: "${NEXUS_SERVICE_NAME}_edit"
  groupNames:
  subjects:
  - kind: ServiceAccount
    name: "${NEXUS_SERVICE_NAME}"
  roleRef:
    name: edit
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NEXUS_SERVICE_NAME}"
    creationTimestamp:
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 0
    selector:
      name: "${NEXUS_SERVICE_NAME}"
    type: ClusterIP
    sessionAffinity: None
parameters:
- name: NEXUS_SERVICE_NAME
  displayName: Nexus3 Service Name
  description: The name of the OpenShift Service exposed for the Nexus3 container.
  value: nexus3
- name: ENABLE_OAUTH
  displayName: Enable OAuth in Nexus3
  description: Whether to enable OAuth OpenShift integration. If false, the static
    account 'admin' will be initialized with the password 'password'.
  value: 'true'
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 4Gi
- name: NAMESPACE
  displayName: Nexus3 ImageStream Namespace
  description: The Nexus3 Namespace where the Nexus3 ImageStream resides.
  value: openshift
- name: NEXUS_IMAGE_STREAM_TAG
  displayName: Nexus3 ImageStreamTag
  description: Name of the ImageStreamTag to be used for the Nexus3 image.
  value: nexusephemeral:latest
labels:
  template: nexus3-ose

