---
apiVersion: v1
kind: Template
labels:
  template: slave-image-ose-template
metadata:
  annotations:
    description: |-
      Jenkins service, without persistent storage.
    iconClass: icon-jenkins
    tags: jenkins
  name: slave-image-ose
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${IMAGE_NAME}
    annotations:
        slave-label: ${SLAVE_LABEL}
    labels:
      role: jenkins-slave
  spec:
    dockerImageRepository: "docker.io/fhwendy/${IMAGE_NAME}"


parameters:
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: IMAGE_NAME
- description: The label
  name: SLAVE_LABEL
