apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
  data:
    password: ${APICAST_CONFIGURATION_URL_BASE64}
  type: Opaque
parameters:
- description: "Name of the secret, if you change this name, be sure to point the 3scale gateway to the correct secret name."
  value: apicast-configuration-url-secret
  name: SECRET_NAME
  required: true
- description: base64 encoded value of the 3scale portal endpoint using this format "https://access-token@test-admin.3scale.net"
  value:
  name: APICAST_CONFIGURATION_URL_BASE64
  required: true
